### ISSUE TITLE
Front and back text colours are wrong

### ISSUE THREAD

**Issue by imclean** [iangr/IGSwitch#4]
You have a bug in your code:
`@IBInspectable var textColorBack: UIColor = UIColor.white {
    didSet {
      backgroundLabels[0].textColor = textColorFront
      backgroundLabels[1].textColor = textColorFront
    }
  }`

should be

`@IBInspectable var textColorBack: UIColor = UIColor.white {
    didSet {
      backgroundLabels[0].textColor = textColorBack
      backgroundLabels[1].textColor = textColorBack
    }
  }`

**Comment by igruenig** [comment]
Thank you. I fixed the bug.
